#!/bin/bash
#Tecan
#Description: add to /usr/local/bin and use


aclocal
automake
autoreconf
autoconf
libtoolize -i
automake --add-missing
./configure

echo " do you want to make ? type y"
read in
if [[ $in == "y" ]]; then
	echo "make"
	$make
	read in
	if [[ $in == "y" ]]; then
		echo "make install"
		sudo make install	
	fi
fi
