#!/bin/bash
#Tecan
#Description: for moving monitor inputs around and turning things on and off to save power.



xrandr --output DVI-I-1  --off
#while read choose monitor type
read
#xrandr --output DVI-I-1 --auto  --left-of HDMI-1 --rotate right
xrandr --output DVI-I-1 --auto --left-of HDMI-1 --rotate right --output HDMI-1 --rotate right --auto

