[Desktop Entry]
Name=OrangeTextDark
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=BlackMATE
MetacityTheme=BlackMATE
IconTheme=Alpha-1
GtkColorScheme=fg_color:#4469ae83dcb4,bg_color:#2bd82bd82bd8,text_color:#9b2ec790dae2,base_color:#1ad71ad71ad7,selected_fg_color:#d0b17c561950,selected_bg_color:#283756de5b07,tooltip_fg_color:#000000000000,tooltip_bg_color:#ffffffffbfbf
CursorTheme=mate
CursorSize=24
NotificationTheme=Coco
