[Desktop Entry]
Name=thedone
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=BlackMATE
MetacityTheme=BlackMATE
IconTheme=Alpha-1
GtkColorScheme=fg_color:#3f96b29be3ea,bg_color:#3e3e3f3f3e3e,text_color:#000000000000,base_color:#5e5b5e5b5e5b,selected_fg_color:#000000000000,selected_bg_color:#485b6abf5475,tooltip_fg_color:#000000000000,tooltip_bg_color:#ffffffffbfbf
CursorTheme=mate
CursorSize=24
NotificationTheme=Coco
