[Desktop Entry]
Name=1test-menta
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Menta
MetacityTheme=BlackMATE
IconTheme=menta
GtkColorScheme=fg_color:#6b5a6b5a6b5a,bg_color:#2d6b2d6b2d6b,text_color:#1ad71ad71ad7,base_color:#652965296529,selected_fg_color:#884288428842,selected_bg_color:#cccccccccccc,tooltip_fg_color:#000000000000,tooltip_bg_color:#f5f5f5f5b5b5
CursorTheme=mate
CursorSize=18
NotificationTheme=Coco
