[Desktop Entry]
Name=AAA
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=BlackMATE
MetacityTheme=BlackMATE
IconTheme=Alpha-1
GtkColorScheme=fg_color:#b9ceb9ceb9ce,bg_color:#421042104210,text_color:#000000000000,base_color:#631863186318,selected_fg_color:#ffffffffffff,selected_bg_color:#55559898d7d7,tooltip_fg_color:#000000000000,tooltip_bg_color:#ffffffffbfbf
CursorTheme=mate
CursorSize=24
NotificationTheme=Coco
BackgroundImage=/usr/share/backgrounds/mate/abstract/Spring.png
