[Icon Theme]
Name=Tuxcursor for Linux Mint (resizable)
Comment=A lovely, animated Tux cursor theme
Name[en_US]=Tuxcursor for Linux Mint (resizable)
Name[de_DE]=Tuxcursor für Linux Mint (in variabler Größe)
Name[eo]=Tuxcursor por Linux Mint (sxangxebla)
Name[es_ES]=Tuxcursor para Linux Mint (redimensionable)
Name[fr_FR]=Tuxcursor pour Linux Mint (redimensionable)
Name[hu_HU]=Tuxcursor Linux Minthez (átméretezhető)
