[Desktop Entry]
Name=newone
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Shiny
MetacityTheme=Shiny
IconTheme=mate
GtkColorScheme=fg_color:#ffffffffffff,bg_color:#508450845084,text_color:#ffffffffffff,base_color:#442144214421,selected_fg_color:#ffffffffffff,selected_bg_color:#55559898d7d7,tooltip_fg_color:#000000000000,tooltip_bg_color:#ffffffffbfbf
CursorTheme=default
CursorSize=18
NotificationTheme=Coco
