[Desktop Entry]
Name=1yaaa
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=BlackMATE
MetacityTheme=BlackMATE
IconTheme=Alpha-1
GtkColorScheme=fg_color:#9409a447b888,bg_color:#252925292529,text_color:#489cb507f9c8,base_color:#463146314631,selected_fg_color:#2144ab1f2bf3,selected_bg_color:#0000344a6574,tooltip_fg_color:#000000000000,tooltip_bg_color:#ffffffffbfbf
CursorTheme=mate
CursorSize=24
NotificationTheme=Coco
