[Desktop Entry]
Name=A1
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=BlackMATE
MetacityTheme=BlackMATE
IconTheme=Alpha-1
GtkColorScheme=fg_color:#b9ceb9ceb9ce,bg_color:#252925292529,text_color:#b18cb18cb18c,base_color:#318c318c318c,selected_fg_color:#ffffffffffff,selected_bg_color:#55559898d7d7,tooltip_fg_color:#000000000000,tooltip_bg_color:#ffffffffbfbf
CursorTheme=mate
CursorSize=24
NotificationTheme=Coco
